<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaLgfRt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaLgfRt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXaLgfRt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXaLgfRt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXaLgfRt\App_KernelDevDebugContainer([
    'container.build_hash' => 'XaLgfRt',
    'container.build_id' => '14f95efc',
    'container.build_time' => 1619470341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaLgfRt');
